### ISSUE TITLE
Can't install on Magento 2.2.3

### ISSUE THREAD

**Issue by yamenarahman** [yireo/Yireo_Whoops#7]
`composer error`
`yireo/magento2-whoops 0.0.8 requires symfony/var-dumper 3.2.*`

and the one installed is 4.0.8

**Comment by jissereitsma** [comment]
Hmm, I'm not encountering the same issue. Which version of PHP are you using?

**Comment by yamenarahman** [comment]
7.1

**Comment by jissereitsma** [comment]
And what does `composer depends symfony/var-dumper` tell you?

**Comment by yamenarahman** [comment]
`tightenco/collect  v5.6.17  requires  symfony/var-dumper (>=3.1.10)`

So, if I removed `tightenco/collect` should it work ?

**Comment by jissereitsma** [comment]
Well, if you don't need this `tightenco/collect` package, then I would recommend to remove it. However, if you do need it, check out our new version `0.0.9` of the Whoops package which should fix this.

**Comment by yamenarahman** [comment]
Thanks for fixing this issue and for your quick replies :)

**Comment by jissereitsma** [comment]
Glad it works!
