### ISSUE TITLE
Magento 2.3 compatibility

### ISSUE THREAD

**Issue by luukschakenraad** [yireo/Yireo_Whoops#9]
Hi Jisse,

Could you please add Magento 2.3 compatibility to `composer.json`?

**Comment by jissereitsma** [comment]
Could you explain what is actually not working? I'm able to install the latest version in Magento 2.3 without issues.

**Comment by luukschakenraad** [comment]
I was checking al external modules we use and expected to see 100.3.* in `composer.json`. Now I see `magento/framework` has a current version of `102.0.1` in 2.3.1, so nothing needs to be changed. My bad!
